version: '3.8'

services:
  web:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./service:/app
    env_file:
      - .env
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py loaddata /app/fixtures/admin.json &&
              python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15-alpine
    env_file:
      - .env
